# Generated by Django 3.1.5 on 2021-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20210508_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='largeimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
